version: '3.1'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - '8090:8090'
    command: ["-Djboss.http.port=8090"]
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
      #- KEYCLOAK_LOGLEVEL=DEBUG
      #- ROOT_LOGLEVEL=DEBUG
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=http://localhost:8090/auth
    volumes:
      - ./realm-export.json:/tmp/realm-export.json