version: '3.1'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - '8005:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json

  gateway:
    container_name: gateway
    build: .
    depends_on:
      - keycloak
    ports:
      - '8800:8900'