version: '3.1'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - '8080:8080'
    environment:
      - DB_VENDOR=h2
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm-export.json
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/auth/" ]
      interval: 20s
      timeout: 5s
      retries: 15
    networks:
      - default
  gateway:
    container_name: gateway
    build: .
    depends_on:
      keycloak:
        condition: service_healthy
    restart: on-failure
    ports:
      - '8800'
      - '15672'
    networks:
      - default
      - messagebrokerservice_default

networks:
  default:
    internal: true
  messagebrokerservice_default:
    external: true