server:
  port: 8800

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/Tanuki-Realm
          jwk-set-uri: http://keycloak:8080/auth/realms/Tanuki-Realm/protocol/openid-connect/certs
