spring:
  security:
    oauth2:
      client:
        provider:
          my-keycloak-provider:
            issuer-uri: http://localhost:8005/auth/realms/Tanuki-Realm
  registration:
    keycloak-spring-gateway-client:
      provider: my-keycloak-provider
      client-id: spring-gateway-service
      client-secret: 5bc21c26-d8ab-45dd-a3c8-980b8c37cacf
      authorization-grant-type: authorization_code
      redirect-uri: '{baseUrl}/login/oauth2/code/keycloak'
server:
  port: 8800