server:
  port: 8800

spring:
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/auth/realms/Tanuki-Realm
          jwk-set-uri: http://localhost:8090/auth/realms/Tanuki-Realm/protocol/openid-connect/certs

  rabbitmq:
    host: localhost

logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
